### ISSUE TITLE
Terminal shell should default to bash

### ISSUE THREAD

**Issue by dsblank** [dsblank/jupyter.brynmawr#6]
Not sure why it isn't. Perhaps SHELL is not set in the root process running jupyterhub. Try

```
SHELL=bash jupyterhub ...
```

**Comment by jdavidheiser** [comment]
Did you ever resolve this?  I'm running a Jupyter server as well and would like to do the same thing.

**Comment by dsblank** [comment]
Nope, this is still a problem. Not sure why it works in `ipython notebook` but not from jupyterhub.

**Comment by dsblank** [comment]
This is now fixed in ipython/jupyterhub.

**Comment by YannBrrd** [comment]
Hi,

How do I activate bash now that it is fixed ? 

Thanks.
Yann

**Comment by dsblank** [comment]
Yes, this was fixed in jupterhub. I believe that they were not passing an env variable, but it should work now. You should update all code.

**Comment by YannBrrd** [comment]
Already on 4.1. 

Terminal launches sh. echo $SHELL > /bin/bash, but not launched. Missed something ?
